### ISSUE TITLE
Add shortcode for Silk

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/shortcake-bakery#105]
It should also reverse:

```
<iframe src="//us-states-with-hiv-specific-criminal-laws.silk.co/s/embed/map/collection/states-with-hiv-specific-criminal-laws-1/location/title/on/silk.co/order/asc/states-with-hiv-specific-criminal-law" width="300" height="400" style="height:400px;width:300px;border:0;"></iframe><div style='margin-left:5px;position:relative;margin-top:-33px;margin-bottom:10px;font-size:14px;color:gray;text-align:left;width:50%;text-overflow:ellipsis;overflow:hidden;white-space:nowrap;'>Data from <a target='_blank' style='text-decoration:none;'href='http://us-states-with-hiv-specific-criminal-laws.silk.co'>us-states-with-hiv-specific-criminal-laws.silk.co</a></div>
```

And:

```
<div style='display: inline-block; width: 100%; min-height: 300px;'><div style='position: relative; padding-bottom: 100%; padding-top:25px; height: 0;'><iframe src="//us-states-with-hiv-specific-criminal-laws.silk.co/s/embed/map/collection/states-with-hiv-specific-criminal-laws-1/location/title/on/silk.co/order/asc/states-with-hiv-specific-criminal-law" style="border:0;position: absolute; top:0; left:0; width: 100%;height:100%; min-height: 300px;"></iframe></div><div style='position:relative;margin-top:-33px;margin-bottom:10px;font-size:12px;color:gray;text-align:left;width:50%;text-overflow:ellipsis;overflow:hidden;white-space:nowrap;'>Data from <a target='_blank' style='text-decoration:none;'href='http://us-states-with-hiv-specific-criminal-laws.silk.co'>us-states-with-hiv-specific-criminal-laws.silk.co</a></div></div>
```

**Comment by danielbachhuber** [comment]
I'd like to add an option for controlling the height.

**Comment by danielbachhuber** [comment]
@ryanboswell @FStop here are the default options for Silk ([from this graphic](https://us-states-with-hiv-specific-criminal-laws.silk.co/s/embed/map/collection/states-with-hiv-specific-criminal-laws-1/location/title/on/silk.co/order/asc/states-with-hiv-specific-criminal-law)):

![image](https://cloud.githubusercontent.com/assets/36432/10312484/4d72219e-6c00-11e5-9114-99e64da1536d.png)

I don't know that it makes sense to match those options exactly, because we always want the embed to be responsive.

I'd like to add a height option. But, how should we communicate the fact that 600px tall but 100% wide is way different on desktop than it is on mobile?

**Comment by FStop** [comment]
I would suggest offering choices like this:

- height: 100%, width: 100%, (fully responsive) -> their default
- height: 800px, width: 100% (responsive width)
- height: 600px, width: 100% (responsive width)
...etc
