### ISSUE TITLE
Infogram shortcode

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/shortcake-bakery#11]
Original embed code looks like this:

```
<script id="infogram_0_washington_marijuana_sales" src="//e.infogr.am/js/embed.js?tb6" type="text/javascript"></script><div style="width:100%;border-top:1px solid #acacac;padding-top:3px;font-family:Arial;font-size:10px;text-align:center;"><a target="_blank" href="https://infogr.am/washington_marijuana_sales" style="color:#acacac;text-decoration:none;">washington legal marijuana sales</a> | <a style="color:#acacac;text-decoration:none;" href="https://infogr.am" target="_blank">Create infographics</a></div>
```

From http://blog.seattlepi.com/marijuana/2015/05/05/graphics-washingtons-marijuana-revenue-broken-down-includes-revenue-from-seattle-stores/#31507101=0

**Comment by danielbachhuber** [comment]
@lisaej Could I get a SVG for Infogram when you have a moment? Needs to be the same look as Localmeasure:

![image](https://cloud.githubusercontent.com/assets/36432/7517748/aef1db54-f48b-11e4-8e32-fc2b4927b8ba.png)

**Comment by danielbachhuber** [comment]
Lisa gave me the SVG when we're ready to run with this.

**Comment by davisshaver** [comment]
I am going to pursue a different tag structure than pasted above. The embed code that Infogram gives when you copy it from the tool directly is just an inline `script` tag,
```<script id="infogram_0_washington_marijuana_sales" src="//e.infogr.am/js/embed.js?hbf" type="text/javascript"></script>```, and the `hbf` string is just a tracking mechanism. 

We will generate this embed from the Infogram permalinks, such as `https://infogr.am/women_on_rolling_stone`, which appears to be the same even for long titles, such as `https://infogr.am/this_is_a_test_of_a_really_long_title_just_to_see_how_long_titles_can_be_i_wonder_lets_see`.

**Comment by davisshaver** [comment]
Ran into this bug with tests https://github.com/wp-cli/wp-cli/issues/1833

**Comment by goldenapples** [comment]
@davisshaver See also: https://github.com/wp-cli/wp-cli/issue/1885 and @noppanit's fix in  https://github.com/wp-cli/wp-cli/pull/1886. If you copy the `install-wp-tests.sh` from one of our projects with working tests, you should be able to run tests.
