### ISSUE TITLE
Add theme-dependent shortcodes (Bucket & Scroll Point)

### ISSUE THREAD

**Issue by jimmyandrade** [fusioneng/shortcake-bakery#24]
* https://github.com/jimmyandrade/shortcake-bakery/blob/master/inc/shortcodes/class-bucket.php
* https://github.com/jimmyandrade/shortcake-bakery/blob/master/inc/shortcodes/class-scroll-point.php

These shortcodes could come along with the plug-in, but they should be activated via `add_filter` or `add_theme_support('shortcake-bucket');` and `add_theme_support('shortcake-scroll-point');`.

The theme author should enqueue styles & scripts needed to make these shortcodes work.

**Comment by davisshaver** [comment]
@jimmyandrade I'm not familiar with Bucket or Scroll Point. Can you post screenshots?

**Comment by jimmyandrade** [comment]
Sure!

![image](https://cloud.githubusercontent.com/assets/2307245/9605940/f7b482f8-5096-11e5-9bd0-a73c02cc2704.png)


Hope to be clear...

![image](https://cloud.githubusercontent.com/assets/2307245/9606046/8b12a142-5097-11e5-981e-a9451a3d40ca.png)

**Comment by danielbachhuber** [comment]
I think these make most sense as secondary shortcodes for now.
