### ISSUE TITLE
SVG icon for Rap Genius

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/shortcake-bakery#26]
Rap Genius looks like this:

![image](https://cloud.githubusercontent.com/assets/36432/8282618/d6a9715e-18a6-11e5-9e5a-e636cea67210.png)

It would look much better with a proper SVG icon

**Comment by danielbachhuber** [comment]
@lisaej Want to hook us up when you have a moment?

**Comment by lisaej** [comment]
Is it these guys? http://rap.genius.com/

**Comment by danielbachhuber** [comment]
Yes
