### ISSUE TITLE
Add Scribd as a Post Element

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/shortcake-bakery#34]
From https://fusionnetwork.slack.com/archives/edit-tech/p1435602428002161

**Comment by davisshaver** [comment]
@danielbachhuber Why Scribd over DocumentCloud?

**Comment by danielbachhuber** [comment]
I guess we could do both? Scribd is the one that came up in the Slack conversation.

**Comment by davisshaver** [comment]
@danielbachhuber A couple questions
- Based on the Slack link, it looks like you modified the embed code to be less ugly. If we are adding this to bakery, do we take editorial discretion on the embed code? Or should we just use the default you get when using the Scribd "get embed code" function?
- There is an existing WordPress.com/Jetpack shortcode for Scribd (more of a an FYI).
- The embed features a lot of options. Along the lines of the first question, how many of the options do we need to expose in Shortcake?

**Comment by danielbachhuber** [comment]
> Based on the Slack link, it looks like you modified the embed code to be less ugly. If we are adding this to bakery, do we take editorial discretion on the embed code? Or should we just use the default you get when using the Scribd "get embed code" function?

Not 100% sure I follow. Can you clarify?

> The embed features a lot of options. Along the lines of the first question, how many of the options do we need to expose in Shortcake?

Your discretion. We should start with some basic set, and add more.

**Comment by danielbachhuber** [comment]
:ship:
