### ISSUE TITLE
PDF shortcode currently requires document be hosted on HTTPS

### ISSUE THREAD

**Issue by davisshaver** [fusioneng/shortcake-bakery#58]
Console error discovered during testing.

```
Mixed Content: The page at 'https://mozilla.github.io/pdf.js/web/viewer.html?file=http%3A%2F%2Fshortcake.local%2Fwp-content%2Fuploads%2F2015%2F07%2F14-556_3204.pdf' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://shortcake.local/wp-content/uploads/2015/07/14-556_3204.pdf'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by danielbachhuber** [comment]
Because `http://mozilla.github.io/` also loads, I suspect we could just look at the protocol for the PDF, and match it on Github.

**Comment by davisshaver** [comment]
@danielbachhuber Should we internalize `pdf.js` to the plugin? See [this post](http://fusion.net/story/31465/here-are-the-best-parts-of-the-leaked-budget-for-the-interview-north-koreas-least-favorite-movie/) – seems like the experience is broken in prod. Has there been a CORS change on the `https://mozilla.github.io` URL?

**Comment by danielbachhuber** [comment]
> Should we internalize pdf.js to the plugin?

I tried previously, but it's more effort than it's worth. Pdf.js only does one small part of it. There's a lot of player JS too

It's broken in prod because I never got around to uploading the PDF in that post to assets.fusion.net. Kit repurposed the static subdomain a while back.

**Comment by danielbachhuber** [comment]
> It's broken in prod because I never got around to uploading the PDF in that post to assets.fusion.net.

I uploaded the PDF to assets.fusion.net, added a CORS policy to the S3 bucket, updated the post, and it still doesn't work :( We might need to pull the PDF shortcode from the bakery...

**Comment by danielbachhuber** [comment]
Let me debug some this morning with @noppanit to make sure it's not a configuration issue.

**Comment by danielbachhuber** [comment]
Ah, fixed now. Must've been browser cache. You can use this as the example:

`[pdf url="https://assets.fusion.net/edit/pdfs/the_interview_budget_excerpts.pdf"]`
