### ISSUE TITLE
Facebook shortcode iFrames not resizing on clean WP install

### ISSUE THREAD

**Issue by davisshaver** [fusioneng/shortcake-bakery#59]
Used URL from the test: `[facebook url="https://www.facebook.com/willpd/posts/1001217146572688"]`

![screen shot 2015-07-15 at 8 47 42 am](https://cloud.githubusercontent.com/assets/1636964/8698695/3680406a-2ace-11e5-9809-953cc641ad35.png)

**Comment by danielbachhuber** [comment]
It works in the theme because we still have this:

```
add_action( 'shortcode_ui_after_do_shortcode', function( $shortcode ) {
	echo \Fusion\Objects\Video::get_footer_embed_script();
	echo \Fusion\Shortcode_Manager::get_shortcake_admin_dependencies();
	if ( false !== stripos( $shortcode, '[fusion-facebook-post' ) ) {
		echo '<script src="' . esc_url( '//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=' . FUSION_FACEBOOK_APPID . '&version=v2.0' ) . '"></script>';
	}
});
```

That our dependencies are loaded in the preview is something we should probably have tests for.

**Comment by davisshaver** [comment]
Pull request started here. Still investigating. https://github.com/fusioneng/shortcake-bakery/pull/64/files
