### ISSUE TITLE
Readme needs updating within WordPress.org repository

### ISSUE THREAD

**Issue by davisshaver** [fusioneng/shortcake-bakery#68]
Our readme on WordPress.org appears to be bust.

<img width="843" alt="screen shot 2015-07-22 at 7 24 41 am" src="https://cloud.githubusercontent.com/assets/1636964/8825179/bd3c76a4-3042-11e5-9161-e3b9063c8ea0.png">

Here's what the readme.txt should contain: https://github.com/fusioneng/shortcake-bakery/blob/master/readme.txt

**Comment by davisshaver** [comment]
@danielbachhuber, the "push to .org" part of this process still opaque to me. What can I do to help with this?

**Comment by danielbachhuber** [comment]
> Our readme on WordPress.org appears to be bust.

There was a minor issue with the readme formatting that caused everything to break 9b85148b2cbde200bbd893a187589d032ff2dcb6

> the "push to .org" part of this process still opaque to me

I am still aware of this.

> What can I do to help with this?

Reporting is sufficient. I can fix these sorts of things.
