### ISSUE TITLE
Allow iframes to opt-in to becoming "responsive"

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/shortcake-bakery#7]
As a nice utility feature, we should let iframe-based shortcodes to opt-in to becoming "responsive". This shouldn't be a user-facing option, but rather something a developer can enable for their shortcode.

**Comment by davisshaver** [comment]
@danielbachhuber - I can take this on. What are your implementation thoughts? The most general I can think of: Adding new `responsive => true` prop that, when true, enqueues a responsive helper JS. However I'm not sure how we would get the class into the shortcode output in an abstracted way, it seems that this might need to be a documentation/implementation chore for shortcodes to add a `shortcake-responsive` class where applicable.

**Comment by danielbachhuber** [comment]
> What are your implementation thoughts?

We already have this in the theme, which has worked well for us to date. I ported the basis for it over in #31 I think all iframes produced by Shortcake Bakery should be responsive by default (e.g. no registration argument), which means we primarily just need to ensure they have the `shortcake-bakery-responsive` argument.

**Comment by davisshaver** [comment]
@danielbachhuber Thanks for the clarification. So I've taken a deeper look and have another question.

We are currently enqueuing the helper JS on all pages with bakery shortcodes. So the "registration" seems like it just needs to be the addition of the `shortcake-bakery-responsive` class to the shortcode template (e.g. within the callback).

Do you see the registration working some other way within the current abstraction? And then, adding conditional logic to only enqueue the JS where the registration is true? We can do this, but it seems like possible overkill at the current time given the desire to just make bakery shortcodes responsive.

**Comment by danielbachhuber** [comment]
> Do you see the registration working some other way within the current abstraction?

Nah, I think the class approach is sufficient. It seems to be working reasonably well now.
