### ISSUE TITLE
Add Twitter shortcode

### ISSUE THREAD

**Issue by davisshaver** [fusioneng/shortcake-bakery#70]
We had a bit of confusion today regarding proper use of Twitter embeds. Producer dropped in the Twitter embed, and so when the `script` was removed, the embed appeared broken on the frontend.

A reversal from Twitter embed to shortcode might be nice. And depending what we think through in https://github.com/fusioneng/shortcake-bakery/issues/5, maybe we want to add reversal for the clean link (typical oembed) usage.

**Comment by danielbachhuber** [comment]
This was added in #88
