### ISSUE TITLE
Add shortcode for Soundcloud

### ISSUE THREAD

**Issue by danielbachhuber** [fusioneng/shortcake-bakery#96]
It should also reverse this:

```
<iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/208170049&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>
```

**Comment by danielbachhuber** [comment]
A bit of a problem :( 

SoundCloud embed uses a track ID, which doesn't resolve to a URL on the website. Nor is there a way to pass the website URL to the embed endpoint.

**Comment by danielbachhuber** [comment]
Oh, I lied. API endpoint will redirect a provided track URL.

**Comment by goldenapples** [comment]
:ship:

**Comment by danielbachhuber** [comment]
I have a few settings I want to add to this shortcode when I have a moment.
